name: Convert To PDF
on:
  workflow_dispatch:
  push:
    branches:
      - Key5n/main
      - main
    paths-ignore:
      - "*.png"
      - "*.jpeg"

jobs:
  marp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: convert to pdf
        id: convertToPDF
        run: |-
          npx -y @marp-team/marp-cli@latest ./main.md -o output.pdf --theme-set themes/style.css
    
      - name: upload as an artifact
        uses: actions/upload-artifact@v3
        if: ${{ steps.convertToPDF.outcome == 'success' }}
        with:
          name: output
          path: output.pdf
          retention-days: 1