name: Convert To PDF
on:
  push:
  workflow_dispatch:

jobs:
  marp:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: convert to pdf
        run: |-
          npx -y @marp-team/marp-cli@latest ./git.md -o ./git.pdf --theme-set themes/style.css

      - name: push to the repo
        run: |-
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "bot: generate a pdf file"
          git push
