name: Convert To PDF
on:
  workflow_dispatch:

jobs:
  marp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: convert to pdf
        id: convertToPDF
        run: |-
          npx -y @marp-team/marp-cli@latest ./git.md -o output.pdf --theme-set themes/style.css
          npx -y @marp-team/marp-cli@latest --images png git.md --theme-set themes/style.css
    
      - name: upload as an artifact
        uses: actions/upload-artifact@v3
        if: ${{ steps.convertToPDF.outcome == 'success' }}
        with:
          name: output_pdf
          path: output.pdf
          retention-days: 1

      - name: upload images as an artifact
        uses: actions/upload-artifact@v3
        if: ${{ steps.convertToPDF.outcome == 'success' }}
        with:
          name: output_png
          path: |
            *.png
          retention-days: 1