name: Convert To PDF
on:
  push:
  workflow_dispatch:

jobs:
  convert:
    name: convert to pdf
    runs-on: ubuntu-latest
    container:
      image: marpteam/marp-cli
    # permissions:
    #   contents: write
    steps:
      - name: log node version
        run: node -v
      # - uses: actions/checkout@v3
      - name: log node version
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: "/bin/echo"
          args: "Hello World"
      - name: log node version2
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: "/usr/local/bin/node"
          args: -v
